openapi: 3.0.0
info:
  title: API
  description: Report of monaco 2018 api
  version: 1.0.0
servers:
  - url: http://localhost/api/v1

paths:
  /report:
    get:
      summary: Returns report of monaco.
      responses:
        '200': # status code
          description: A JSON array of racers with team and lap_time
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
            type: string
            application/xml: # Another media types
              schema:
                type: object
  /report/racers:
    get:
      summary: Returns racers list.
      responses:
        '200': # status code
          description: A JSON array of racers with team and lap_time
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
            application/xml: # Another media types
              schema:
                type: object
  /report/racers/id={abbreviation}:
    get:
      summary: Returns racer info.
      responses:
        '200': # status code
          description: A JSON array of racers with team and lap_time
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
            application/xml: # Another media types
              schema:
                type: object

